### ISSUE TITLE
centos copy after download in the same directory fails

### ISSUE THREAD

**Issue by pratikch** [AlbanAndrieu/ansible-eclipse#12]
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/copy.py", line 457, in run
    source = self._find_needle('files', source)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 986, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 386, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])
AnsibleFileNotFound: Could not find or access '/tmp/eclipse-jee-oxygen-M6-linux-gtk-x86_64.tar.gz'

fatal: [ide]: FAILED! => {
    "changed": false, 
    "msg": "Could not find or access '/tmp/eclipse-jee-oxygen-M6-linux-gtk-x86_64.tar.gz'"
}
	to retry, use: --limit @/home/vagrant/ansiblescripts/install_eclipse.retry

**Comment by AlbanAndrieu** [comment]
If you cannot access your /tmp. Try overriding : eclipse_dir_tmp: "{{ tempdir.stdout }}" to somewhere you have access
